### ISSUE TITLE
Invalid mysql service start command after machine reboot

### ISSUE THREAD

**Issue by xmik** [chef-cookbooks/mysql#303]
Using mysql cookbook version 6.0.13, chef 11.16.4, provisioning with vagrant in virtual machine with debian 7.5, after machine reboot one can login to mysql server (different instance?) as root with no password. 

My recipe:

```ruby
include_recipe 'apt'

mysql_instance = 'default'
mysql_service mysql_instance do
  provider Chef::Provider::MysqlService::Sysvinit
  port '3306'
  version '5.5'
  initial_root_password node['mysql']['server_root_password']
  action [:create, :start]
end

mysql_config mysql_instance do
  source 'default.cnf.erb' # empty file (http://stackoverflow.com/questions/27823274/install-mysql-cookbook-with-vagrant-and-chef-solo)
  version '5.5'
  notifies :restart, "mysql_service[#{mysql_instance}]"
  action :create
end
```

After provisioning, inside virtual machine:
```bash
vagrant@one-5128:~$ cat /etc/debian_version 
7.5
vagrant@one-5128:~$ ps aux | grep mysql
root      5708  0.0  0.0   4184   708 ?        S    16:12   0:00 /bin/sh /usr/bin/mysqld_safe --defaults-file=/etc/mysql-default/my.cnf
mysql     5881  0.1  1.9 338740 39848 ?        Sl   16:12   0:00 /usr/sbin/mysqld --defaults-file=/etc/mysql-default/my.cnf --basedir=/usr --datadir=/var/lib/mysql-default --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql-default/error.log --pid-file=/run/mysql-default/mysqld.pid --socket=/run/mysql-default/mysqld.sock --port=3306
vagrant   6009  0.0  0.0   7836   872 pts/0    S+   16:13   0:00 grep mysql 
vagrant@one-5128:~$ mysql -u root -h 127.0.0.1
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
vagrant@one-5128:~$ mysql -u root -h 127.0.0.1 -p
Enter password:
mysql> exit
Bye
 ```
After machine reboot:
```bash
vagrant@one-5128:~$ ps aux | grep mysql
root      2355  0.0  0.0   4180   696 ?        S    16:17   0:00 /bin/sh /usr/bin/mysqld_safe
mysql     2513  0.4  2.0 338740 41600 ?        Sl   16:17   0:00 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/lib/mysql/one-5128.err --pid-file=/var/lib/mysql/one-5128.pid
vagrant   4023  0.0  0.0   7836   872 pts/0    S+   16:18   0:00 grep mysql
vagrant@one-5128:~$ mysql -u root -h 127.0.0.1 
mysql> select host,user,password from mysql.user;
+-----------+------------------+-------------------------------------------+
| host      | user             | password                                  |
+-----------+------------------+-------------------------------------------+
| localhost | root             |                                           |
| one-5128  | root             |                                           |
| 127.0.0.1 | root             |                                           |
| ::1       | root             |                                           |
| localhost | debian-sys-maint | *28F59948607009F7EC264C1C87A3EFB8B6146573 |
+-----------+------------------+-------------------------------------------+
5 rows in set (0.00 sec)
mysql> exit
Bye
vagrant@one-5128:~$ mysql -u root -h 127.0.0.1 -p
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

It is resolved (until the next reboot) with the following:
```bash
vagrant@one-5128:~$ sudo service mysql stop
[ ok ] Stopping MySQL database server: mysqld.
vagrant@one-5128:~$ sudo /bin/sh /usr/bin/mysqld_safe --defaults-file=/etc/mysql-default/my.cnf
```
Edit:
actually enough is:
```bash
vagrant@one-5128:~$ sudo service mysql stop
vagrant@one-5128:~$ sudo service mysql-default start
```

**Comment by someara** [comment]
Looks like it's not correctly disabling the system service...
Consider this triaged!

-s

**Comment by someara** [comment]
Hello!

I've fixed this up in master... it will ship in the next release!

https://github.com/chef-cookbooks/mysql/commit/e33580d68d78344bd2a5983dd5c8a9413540905b

-s

**Comment by xmik** [comment]
Thanks! I've tested using mysql cookbook version 6.0.15 and I confirm it is fixed.

**Comment by zacharyblank** [comment]
I am still seeing this behavior under Vagrant, Virtualbox, Ubuntu 14.10 and cookbook 6.0.17 after rebooting a box. Creating for the first time works fine.

**Comment by ejjaquet** [comment]
I am still seeing this behaviour in Debian, using version 8.01 from the Cookbook. After a reboot, the default service starts and not my installed service
